import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import React from "react";
import BG from "@/images/BG.jpg";
import Head from "next/head";

const poppins = Poppins({ subsets: ["latin"], weight: "200" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const imageUrl = "/image/BG.jpg";

  return (
    <html className="!scroll-smooth  md:scroll-auto">
      <head>
        <title>Sastra</title>
      </head>
      <body className={poppins.className}>
        <div className=" ">
          <Navbar />
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
